name: Run tests and upload coverage

on:
  push

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24.3

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.out

      - uses: qltysh/qlty-action/coverage@v1.0.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.out